# Generated by Django 2.2.24 on 2021-12-11 17:17

from django.db import migrations

import phonenumbers

def normalize_phonenumber(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        ru_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        flat.owner_pure_phone = f'+{ru_number.country_code}{ru_number.national_number}'
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20211211_2000'),
    ]

    operations = [
        migrations.RunPython(normalize_phonenumber),
    ]
