# Generated by Django 2.2.24 on 2021-12-13 09:25

from django.db import migrations


def define_owner_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        for flat in (
            Flat.objects.filter(owner=owner.name)
            .filter(owner_pure_phone=owner.pure_phone)
            ):
            owner.flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20211213_1224'),
    ]

    operations = [
        migrations.RunPython(define_owner_flats),
    ]
